services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SSH_HOST=${SSH_HOST}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PASSWORD=${SSH_PASSWORD}
    volumes:
      - ./backend:/app  # Optional for development
      - /app/node_modules
 
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend